name: mem0-dev

services:
  mem0:
    build:
      context: ..
      dockerfile: server/dev.Dockerfile
    ports:
      - "8888:8000"
    env_file:
      - .env
    networks:
      - mem0_network
      - dokploy-network
    volumes:
      - ./history:/app/history
      - .:/app
      - ../mem0:/app/packages/mem0
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mem0-api.rule=Host(`mem0.enginecy.cloud`)"
      - "traefik.http.routers.mem0-api.entrypoints=websecure"
      - "traefik.http.routers.mem0-api.tls=true"
      - "traefik.http.routers.mem0-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.mem0-api.loadbalancer.server.port=8000"

  mem0-ui:
    build:
      context: ../openmemory/ui
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=https://mem0.enginecy.cloud
    networks:
      - mem0_network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mem0-ui.rule=Host(`dashboard.mem0.enginecy.cloud`)"
      - "traefik.http.routers.mem0-ui.entrypoints=websecure"
      - "traefik.http.routers.mem0-ui.tls=true"
      - "traefik.http.routers.mem0-ui.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.mem0-ipwhitelist.ipwhitelist.sourcerange=47.196.5.145/32"
      - "traefik.http.routers.mem0-ui.middlewares=mem0-ipwhitelist"
      - "traefik.http.services.mem0-ui.loadbalancer.server.port=3000"
    depends_on:
      - mem0

  postgres:
    image: ankane/pgvector:v0.5.1
    restart: on-failure
    shm_size: "128mb"
    networks:
      - mem0_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "8432:5432"

  neo4j:
    image: neo4j:5.26.4
    networks:
      - mem0_network
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 90s
    ports:
      - "8474:7474"
      - "8687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/mem0graph
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

volumes:
  neo4j_data:
  postgres_db:

networks:
  mem0_network:
    driver: bridge
  dokploy-network:
    external: true
